### ISSUE TITLE
WebGL Requirement

### ISSUE THREAD

**Issue by KS-HTK** [soerface/7billionhumans#17]
WebGL not supported by all browser. There is no fallback for webGL. For such small graph webGL should not be relevant.

**Comment by landfillbaby** [comment]
maybe migrate from plot.ly (webGL) to [Chart.js](//chartjs.org) (HTML5 canvas)?

**Comment by landfillbaby** [comment]
oh, or we could just try switching plotly from WebGL mode to SVG mode

**Comment by landfillbaby** [comment]
oh it turns out the reason it doesn't work on mobile is https://github.com/plotly/plotly.js/pull/2997

**Comment by landfillbaby** [comment]
if you update the local plotly to >= 1.41.1 it should work
