### ISSUE TITLE
Overwriting of existing solutions faulty.

### ISSUE THREAD

**Issue by KS-HTK** [soerface/7billionhumans#8]
```
Target Size: 17
Size: 17
Target Speed: 54
Speed: 52
Copy the sourcecode to the clipboard and press enter


Saved:                                        solutions/64 - Binary Counter/size.asm
Saved:                                       solutions/64 - Binary Counter/speed.asm
Saved:                                      solutions/64 - Binary Counter/speed+size.asm

Add another source? [y/N] y
Target Size: 17
Size: 17
Target Speed: 54
Speed: 47
Copy the sourcecode to the clipboard and press enter


Saved:                                        solutions/64 - Binary Counter/size.asm
Saved:                                       solutions/64 - Binary Counter/speed.asm
Already exists, not overwriting:            solutions/64 - Binary Counter/speed+size.asm
```

As indicated by the output: my second solution was slightly faster but it did not overwrite the speed+size of my first attempt.

**Comment by tiansh** [comment]
I would suggest rename from `speed.asm` / `size.asm` to something like `speed-48-size-32.asm`. Since we cannot decide which one of speed-34-size-40, and, speed-40-size-34 is better.

**Comment by KS-HTK** [comment]
That is why speed.asm would be speed-34-size-40 and size.asm would be speed-40-size-34.
It saves the best version you have put in for the particular challenge as speed.asm or size.asm.
The problem was, that this did not apply to speed+size. That is why this Issue was created. Now it will also overwrite speed+size if one is better and the other one did not change.

**Comment by tiansh** [comment]
@KS-HTK If we have multiple solutions for some level whose `(size, speed)` are `(10, 200)`, `(12, 80)`, `(20, 76)`, `(40, 60)`. Then you will chose `(10, 200)` for `size.asm` and `(40, 60)` for `speed.asm`. But which one for `speed+size` now? My suggestion is keeping all of theme as long as some solution is creative and be better than others in any one of these indexes.

**Comment by soerface** [comment]
@tiansh I like the idea of just keeping multiple solutions. I would not keep "creative" solutions since that criterium is very subjective. But discarding any solution that is not better in any way than another solution. Thanks to @ansvonwa for suggesting this graphic (I just needed it to recreate it, not very pretty): https://i.imgur.com/Y1scAkN.png

I'm trying to implement this visualization for the GitHub pages site. Maybe even showing the according GitHub Avatar for each solution!

**Comment by soerface** [comment]
Done, further suggestions welcome: https://soerface.github.io/7billionhumans/33-Data_Backup_Day/
